- name: create welcome.txt text file
  copy:
    src: "welcome.txt"
    dest: "welcome.txt"
    owner: root
    group: root
    mode: "0644"

- name: add useful aliases
  lineinfile:
    path: ".bashrc"
    line: "alias welcome = 'cat welcome.txt'"
    create: yes
