- name: Create group "kayttajat"
  group:
    name: "kayttajat"
    state: present

- name: Create user kayttaja
  user:
    name: kayttaja
    state: present
    create_home: yes

- name: add sudo rights to kayttajat group
  copy:
    dest: "/etc/sudoers.d/kayttajat"
    content: "%sudoless ALL = (ALL) NOPASSWD: ALL\n"
    owner: root
    group: root
    mode: "0644"
